### PR TITLE
Update a Test Run with results

### PR DESCRIPTION
**Pull request by webmagit**
Please review what I believe is a fix for updating a Run!

### CODE REVIEW

**Comment by gavin771** [comment]
Sure!!

**Comment by CalvinMcstein** [comment]
Hey @gavin771 nudge to get this reviewed/pushed :-)

**Comment by raulrubioa** [comment]
Hey! is there a plan to merge this PR anytime soon? I tried it and it worked fine! 

I need this for the wdio+testrail integration 😄

**Comment by gavin771** [comment]
merged @raulrubioa @CalvinMcstein @webmagit

**Pull request merged**
